### ISSUE TITLE
The operation couldn't be completed. No such file or directory.

### ISSUE THREAD

**Issue by whoisgrayson** [nicolodiamante/keyave#1]
I installed everything correctly and then added the shortcut to my shortcuts and pressed play, then a pop up box appeared saying "allow "passwords" to access your file 'Passwords.prefsPane"? I then clicked YES but then another pop up box appeared saying "The operation couldn't be completed. No such file or directory".

I am running macOS Sonoma 14.2.1

Does anyone know what I am doing wrong? Thanks

<img width="1470" alt="Screenshot 2024-01-14 at 11 05 59 PM" src="https://github.com/nicolodiamante/keyave/assets/155737385/06568591-9df6-4dc3-809a-eff7c9f7bde8">
<img width="1470" alt="Screenshot 2024-01-14 at 11 06 03 PM" src="https://github.com/nicolodiamante/keyave/assets/155737385/f1b071c5-dac0-4a19-a196-bbbbb200d434">

**Comment by nicolodiamante** [comment]
Hi @whoisgrayson ,

The issue is related to the path or location of the file 'Passwords.prefsPane' that the shortcut is trying to access. The path on macOS Sonoma 14.2.1  has been changed, I'm going shortly update the page with the new link to download it. In the mean time try with this one [here](https://www.icloud.com/shortcuts/66d085e26582484b908d9bb2cb9bceee).

**Comment by nicolodiamante** [comment]
Hello @whoisgrayson,

I wanted to let you know that I've made updates to both the script and shortcut. You are welcome to visit the [Keyave page](https://github.com/nicolodiamante/keyave), where you can find the latest version. If you have any questions or need further assistance, please feel free to reach out.

**Comment by whoisgrayson** [comment]
Hey

Thank you so much, It is now working perfectly!

Thanks for the help

Grayson

From: Nicolò Diamante ***@***.***>
Date: Tuesday, 16 January 2024 at 2:14 am
To: nicolodiamante/keyave ***@***.***>
Cc: whoisgrayson ***@***.***>, Mention ***@***.***>
Subject: Re: [nicolodiamante/keyave] The operation couldn't be completed. No such file or directory. (Issue #1)

Hello @whoisgrayson<https://github.com/whoisgrayson>,

I wanted to let you know that I've made updates to both the script and shortcut. You are welcome to visit the Keyave page<https://github.com/nicolodiamante/keyave>, where you can find the latest version. If you have any questions or need further assistance, please feel free to reach out.
